receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 86.109.5.33:4317

exporters:
  clickhouse:
    endpoint: http://136.144.49.85:9000?dial_timeout=10s&compress=lz4
    connection_params:
      async_insert: 1
      wait_for_async_insert: 1
      async_insert_threads: 100
      async_insert_max_data_size: 40000000
      async_insert_busy_timeout_ms: 1000
      async_insert_deduplicate: 0
    username: default
    database: default
    traces_table_name: otel_traces
    timeout: 5s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
    sending_queue:
      queue_size: 1000000

service:
  pipelines:
    traces:
      receivers:
      - otlp
      exporters:
      - clickhouse
