receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 147.28.182.5:4317

exporters:
  clickhouse:
    endpoint: tcp://145.40.99.37:9000?dial_timeout=10s&compress=lz4
    username: default
    database: default
    traces_table_name: otel_traces
    timeout: 5s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
    sending_queue:
      queue_size: 100000

service:
  pipelines:
    traces:
      receivers:
      - otlp
      exporters:
      - clickhouse
